version: '3.3'
services:
    
    mongodb:
        image: mongo
        networks: 
            - production-network

    node1:
        
        build:
            dockerfile: ./docker/desafio.dockerfile
            context: .
        volumes: 
            - .:/var/www               
        
        image: node
        container_name: totvs-chamados
        ports:
            - "3000:3000"
        networks: 
            - production-network
        depends_on:
            - "mongodb"
   

networks: 
    production-network:
        driver: bridge

volumes:
    .: